export { default as BackIcon } from './back.svg';
export { default as CrownIcon } from './crown.svg';
export { default as EyeShowIcon } from './eye-show.svg';
export { default as FemaleIcon } from './female.svg';
export { default as LoveIcon } from './love.svg';
export { default as PoopNormalIcon } from './poop-normal.svg';
export { default as MaleIcon } from './male.svg';
export { default as UnknownIcon } from './unknown.svg';
export { default as NotFoundIcon } from './404.svg';